add plz
DinGo42/messenger pull request #3
Opened 2022-10-26 16:31 UTC by DinGo42

2022-10-26 17:52 UTC, Angoliuk requested changes

2022-10-26 17:52 UTC, Angoliuk commented on database.js
> +  l_database = JSON.parse(localStorage.getItem('database')) ?? {}
`localStorage.getItem('database')` може бути `null` і випаде помилка, тому спочатку перевіряй, чи у нас взагалі `localStorage.getItem('database')` щось повертає

2022-10-26 17:52 UTC, Angoliuk commented on database.js
> +      if(collection_type[collection][field].unique){
Ти вручну перевіряєш, чи є повинно бути поле унікальне. А якщо у колекції буде 10 перевірок, тоді і 10 if? Можеш автоматично підбирати перевірку, як ми робили із валідацією інпутів при логіні

2022-10-26 17:52 UTC, Angoliuk commented on database.js
> +if(is_valid){
Зайва вкладенність, краще пиши `if (!is_valid) return;`

2022-10-26 17:52 UTC, Angoliuk commented on database.js
> +  saveToLocalStorage()
Зараз у тебе буде визиватись `saveToLocalStorage()` навіть якщо поле не валідне, навіщо?

2022-10-26 17:52 UTC, Angoliuk commented on database.js
> +  return
Можна і без цього `return`

2022-10-26 17:52 UTC, Angoliuk commented on database.js
> +const find = (condition_obj,collection) =>{
Не працює

2022-10-26 17:52 UTC, Angoliuk commented on footer.js
> +  full.insertAdjacentElement("beforeend", loginBar);
full is undefined

2022-10-26 17:52 UTC, Angoliuk commented on footer.js
> +  login.classList = "buttons-reg";
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on footer.js
> +  sign.classList = "buttons-reg";
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on footer.js
> +  buttons_div.classList = "buttons-div";
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on lockScreen&Inputs.js
> +  lock_div.classList = "login-lock";
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on lockScreen&Inputs.js
> +  login_window.classList = "login-window";
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on lockScreen&Inputs.js
> +  submit.classList = "buttons-reg";
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on lockScreen&Inputs.js
> +  input.classList = obj.input_class;
Замість переписування classList краще використовувати його методи типу classList.add("style")
https://www.w3schools.com/howto/howto_js_add_class.asp

2022-10-26 17:52 UTC, Angoliuk commented on lockScreen&Inputs.js
> +function createInputs(
`createInputs` створює один інпут, хоча назва в множині

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    color: white;
краще винести кольори в змінні

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    color: white;
і краще пиши не назву кольору, а кодом. Типу `#fff` / `#ffffff` etc.

2022-10-26 17:52 UTC, Angoliuk commented on lockScreen&Inputs.js
> +  submit.onclick = () => {
краще функцію виносити в змінну, а в `onclick` просто її присвоювати

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background: #121212;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background: #121212;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    border: solid 2px #f2f2f2;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background: rgba(129, 16, 16, 0);;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    color: white;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background: #121212;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background-color: #fff;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    color: #fff;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background-color: #2EE59D;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    color: #2EE59D;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background: gray;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    background: gray;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on main_style_massager.css
> +    color: #2EE59D;
краще винести кольори в змінні i пиши не назву кольору, а кодом. Типу #fff / #ffffff etc.

2022-10-26 17:52 UTC, Angoliuk commented on objectModel.js
> +  required:(obj,collection,field) => obj[field],
collection змінна не використовується

2022-10-26 17:52 UTC, Angoliuk commented on objectModel.js
> +const user_model = {
А який сенс collection_type? Ти можеш додати required і unique поля в модель. Якщо тобі треба, щоб у тебе всі моделі були в одному об`єкті, то можеш їх поєднати

2022-10-26 17:52 UTC, Angoliuk commented on userObject.js
> +  addObject({title:'hello',text:'test of new object model',email:'test123@ukr.net'},'posts')
Як розумію, то це тестові 40, 42-43 строки?
До речі, тобі ж треба визивати addCollection('users') тільки при ініціалізції бд, тому, як варіант, його винести

2022-10-26 17:52 UTC, Angoliuk commented on validation.js
> +    const input = document.getElementById(field_obj.id);
input  може бути null, зроби перевірку

2022-10-26 17:52 UTC, Angoliuk commented on validation.js
> +    submit.disabled = false;
Де ти submit взяв?

2022-10-26 17:52 UTC, Angoliuk commented on validation.js
> +  submit.disabled = true;
Де ти submit взяв?

2022-10-27 08:43 UTC, DinGo42 commented on userObject.js
> +  addObject({title:'hello',text:'test of new object model',email:'test123@ukr.net'},'posts')
куди винести ?

2022-10-29 17:30 UTC, Angoliuk commented on userObject.js
> +  addObject({title:'hello',text:'test of new object model',email:'test123@ukr.net'},'posts')
Тобі ж треба створювати пусті колекції тільки при ініціалізації бд, тому можеш зробити функцію, яка буде ініціалізувати бд і створювати в ній колекції. А визиваєш її при запускі додатку

2022-10-29 17:30 UTC, Angoliuk commented on userObject.js
> +  addObject({title:'hello',text:'test of new object model',email:'test123@ukr.net'},'posts')
Вчасно

2022-12-20 18:34 UTC, closed without merging