resolved all problems
DinGo42/messenger pull request #4
Opened 2022-10-28 21:00 UTC by DinGo42

2022-10-30 08:04 UTC, Angoliuk requested changes

2022-10-30 08:04 UTC, Angoliuk commented on database.js
> +  console.log(obj);
`console.log` не потрібний

2022-10-30 08:04 UTC, Angoliuk commented on footer.js
> +  const full = document.getElementById("full");
Object is possibly 'null'.

2022-10-30 08:04 UTC, Angoliuk commented on footer.js
> +  const full = document.getElementById("full");
full може не існувати

2022-10-30 08:04 UTC, Angoliuk commented on main_style_massager.css
> +:root {
з кольорами намана, але чого назви в різному стилі? Одні словом, одні rgba, інші шістндцятковою

2022-10-30 08:04 UTC, Angoliuk commented on main_style_massager.css
> +:root {
В плані red/rgba(1, 1, 1, 1)/#fff, треба в одному стилі, бажано або rgba або #

2022-10-30 08:04 UTC, Angoliuk commented on objectModel.js
> +const acount_model = {
acount???? Чєл...

2022-10-30 08:04 UTC, Angoliuk commented on objectModel.js
> +const acount_model = {
Буду чекати пояснень, навіщо цей об`єкт, готуйся

2022-10-30 08:04 UTC, Angoliuk commented on userObject.js
> +  // addCollection('posts')
Це досі WIP?

2022-10-30 08:04 UTC, Angoliuk commented on validation.js
> +    const submit = document.getElementById("submit");
Object is possibly 'null'.

2022-10-30 08:04 UTC, Angoliuk commented on validation.js
> +  const submit = document.getElementById("submit");
Object is possibly 'null'.

2022-10-30 08:04 UTC, Angoliuk commented on validation.js
> +  const submit = document.getElementById("submit");
До речі, а нічого, що ти шукаєш по id submit? Сабміт кнопок може бути багато

2022-10-30 08:04 UTC, Angoliuk commented on validation.js
>      const input = document.getElementById(field_obj.id);
Object is possibly 'null'.

2022-10-30 08:04 UTC, Angoliuk commented on objectModel.js
>  const checks = {
Чекає фікса

2022-10-30 08:04 UTC, Angoliuk commented on database.js
> +  if (localStorage.getItem("database")) {
localStorage.getItem("database") ти цю команду визиваєш два рази. Краще перед if запиши результат в змінну

2022-10-30 08:04 UTC, Angoliuk commented on database.js
> +const addObject = (obj, collection) => {
Це подивлюсь, коли checks будуть готові

2022-10-30 09:43 UTC, DinGo42 commented on validation.js
> +  const submit = document.getElementById("submit");
так id унікальне , чи як ?

2022-10-30 10:34 UTC, Angoliuk commented on validation.js
> +  const submit = document.getElementById("submit");
Воно повинне бути унікальне. Просто `submit` досить загальне, і якщо на сторінці дві сабміт кнопки і у них двох буде `id` `submit` то воно поламається. Того краще давати більш точні назви
Перевірити досить легко: зроби дві кнопки з одинаковим id і визви метод `getElementById`, потім зміни параметри у кнопки, яку ти отримав через getElementById, подивись на результат

2022-11-01 17:15 UTC, Angoliuk requested changes

2022-11-01 17:15 UTC, Angoliuk commented on create_DOM_tree.js
> +export const create_DOM = () => {
назва файлу і функції придурошна, ти не створюєш DOM

2022-11-01 17:15 UTC, Angoliuk commented on footer.js
> +  const full = document.getElementById('full')
`full` досі може бути `null`

2022-11-01 17:15 UTC, Angoliuk commented on create_DOM_tree.js
> +export const create_DOM = () => {
і назва файлу snake_case, коли інші файли camelCase

2022-11-01 17:15 UTC, Angoliuk commented on main_style_massager.css
> +:root {
назва файлу snake_case, коли інші файли camelCase

2022-11-01 17:15 UTC, Angoliuk commented on userObject.js
>  };
на 98 перевірка типу в number у тебе `(num) => typeof num === "string"`

2022-11-01 17:15 UTC, Angoliuk commented on validation.js
>    submit.disabled = true;
Object is possibly 'null'

2022-11-01 17:15 UTC, Angoliuk commented on validation.js
>      submit.disabled = false;
Object is possibly 'null'

2022-11-01 17:15 UTC, Angoliuk commented on validation.js
> +    if ((field_obj.required && !input.value) || !input.value === null) {
Object is possibly 'null'

2022-11-02 16:21 UTC, Angoliuk requested changes

2022-11-02 16:21 UTC, Angoliuk commented on createMainTree.js
> +export const createMainHtml = () => {
Блять, який трі??? Просто Main.js. Я їбав

2022-11-02 16:21 UTC, Angoliuk commented on database.js
> +    l_database = JSON.parse(localStorage.getItem("database")) ?? {};
if ти фіксив, але після відкату не повернув

2022-11-02 16:21 UTC, Angoliuk commented on draw_posts.js
> +export const crate_post = (database,div) => {
draw? хуёв
якщо це картка поста, то це post_card

2022-11-02 16:21 UTC, Angoliuk commented on draw_posts.js
> +      setTimeout(()=>document.getElementById('main').addEventListener('click',()=>{
Object is possibly 'null'

2022-11-02 16:21 UTC, Angoliuk commented on mainStyleMassager.css
> +  --color-buttons-reg-enebled: rgba(46, 229, 157, 0.4);
один стиль кольорів

2022-11-02 16:21 UTC, Angoliuk commented on validation.js
> +    if (!input.value) return;
Object is possibly 'null'.     `Input`

2022-11-02 20:57 UTC, DinGo42 commented on database.js
> +    l_database = JSON.parse(localStorage.getItem("database")) ?? {};
а що там за проблема , просто написати  if (!....database)return ?

2022-11-03 20:35 UTC, Angoliuk approved these changes

2022-11-03 20:37 UTC, merged